Issue #443: Add --wait-ready switch for `ktd`
This patch adds a new option switch. The option switch accepts an
optional parameter that represents the amount of seconds it will wait
until considering the run has failed.

To test:
1. Apply this patch
2. Run:

```shell
$ ktd --plugins up -d ; ktd --wait-ready 10 ; echo $?
[+] Running 4/4
 ✔ Network koha_kohanet        Created                                                                                                           0.0s
 ✔ Container koha-memcached-1  Started                                                                                                           0.3s
 ✔ Container koha-db-1         Started                                                                                                           0.3s
 ✔ Container koha-koha-1       Started                                                                                                           0.4s
Attempt 10 of 10
ERROR: no more attempts
1
```

=> FAIL: It fails because 10 seconds is too fast

3. Run:

```shell
$ ktd down
$ ktd --plugins up -d ; ktd --wait-ready 100 ; echo $?
[+] Running 4/4
 ✔ Network koha_kohanet        Created                                                                                                           0.0s
 ✔ Container koha-db-1         Started                                                                                                           0.3s
 ✔ Container koha-memcached-1  Started                                                                                                           0.3s
 ✔ Container koha-koha-1       Started                                                                                                           0.4s
Attempt 55 of 100
0
```

Signed-off-by: Tomas Cohen Arazi <tomascohen@theke.io>